// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netty/MsgBody.proto

package com.abin.lee.im.model.proto;

public final class MsgBodyProto {
  private MsgBodyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.MsgBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 userId = 1 [default = 0];</code>
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 1 [default = 0];</code>
     */
    long getUserId();

    /**
     * <code>required string userName = 2 [default = "NoKnown"];</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2 [default = "NoKnown"];</code>
     */
    String getUserName();
    /**
     * <code>required string userName = 2 [default = "NoKnown"];</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>required string passWord = 3 [default = "NoKnown"];</code>
     */
    boolean hasPassWord();
    /**
     * <code>required string passWord = 3 [default = "NoKnown"];</code>
     */
    String getPassWord();
    /**
     * <code>required string passWord = 3 [default = "NoKnown"];</code>
     */
    com.google.protobuf.ByteString
        getPassWordBytes();

    /**
     * <code>required int32 bodyLength = 4 [default = 0];</code>
     */
    boolean hasBodyLength();
    /**
     * <code>required int32 bodyLength = 4 [default = 0];</code>
     */
    int getBodyLength();

    /**
     * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
     */
    MsgBody.MessageType getMessageType();

    /**
     * <code>repeated string address = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getAddressList();
    /**
     * <code>repeated string address = 6;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated string address = 6;</code>
     */
    String getAddress(int index);
    /**
     * <code>repeated string address = 6;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes(int index);
  }
  /**
   * Protobuf type {@code netty.MsgBody}
   */
  public  static final class MsgBody extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:netty.MsgBody)
      MsgBodyOrBuilder {
    // Use MsgBody.newBuilder() to construct.
    private MsgBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MsgBody() {
      userId_ = 0L;
      userName_ = "NoKnown";
      passWord_ = "NoKnown";
      bodyLength_ = 0;
      messageType_ = 4;
      address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              passWord_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              bodyLength_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              MessageType value = MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                messageType_ = rawValue;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                address_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              address_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          address_ = address_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgBodyProto.internal_static_netty_MsgBody_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgBodyProto.internal_static_netty_MsgBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MsgBody.class, Builder.class);
    }

    /**
     * Protobuf enum {@code netty.MsgBody.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WEB = 1;</code>
       */
      WEB(0, 1),
      /**
       * <code>ANDROID = 2;</code>
       */
      ANDROID(1, 2),
      /**
       * <code>IOS = 3;</code>
       */
      IOS(2, 3),
      /**
       * <code>PLATFORM = 4;</code>
       */
      PLATFORM(3, 4),
      ;

      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>ANDROID = 2;</code>
       */
      public static final int ANDROID_VALUE = 2;
      /**
       * <code>IOS = 3;</code>
       */
      public static final int IOS_VALUE = 3;
      /**
       * <code>PLATFORM = 4;</code>
       */
      public static final int PLATFORM_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return WEB;
          case 2: return ANDROID;
          case 3: return IOS;
          case 4: return PLATFORM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MsgBody.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netty.MsgBody.MessageType)
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>required int64 userId = 1 [default = 0];</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 userId = 1 [default = 0];</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile Object userName_;
    /**
     * <code>required string userName = 2 [default = "NoKnown"];</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2 [default = "NoKnown"];</code>
     */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2 [default = "NoKnown"];</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile Object passWord_;
    /**
     * <code>required string passWord = 3 [default = "NoKnown"];</code>
     */
    public boolean hasPassWord() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string passWord = 3 [default = "NoKnown"];</code>
     */
    public String getPassWord() {
      Object ref = passWord_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          passWord_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string passWord = 3 [default = "NoKnown"];</code>
     */
    public com.google.protobuf.ByteString
        getPassWordBytes() {
      Object ref = passWord_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        passWord_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODYLENGTH_FIELD_NUMBER = 4;
    private int bodyLength_;
    /**
     * <code>required int32 bodyLength = 4 [default = 0];</code>
     */
    public boolean hasBodyLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 bodyLength = 4 [default = 0];</code>
     */
    public int getBodyLength() {
      return bodyLength_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 5;
    private int messageType_;
    /**
     * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
     */
    public MessageType getMessageType() {
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.PLATFORM : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList address_;
    /**
     * <code>repeated string address = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      return address_;
    }
    /**
     * <code>repeated string address = 6;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated string address = 6;</code>
     */
    public String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated string address = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassWord()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBodyLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, userName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, passWord_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, bodyLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, messageType_);
      }
      for (int i = 0; i < address_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, address_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, userName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, passWord_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, bodyLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, messageType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += computeStringSizeNoTag(address_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static MsgBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MsgBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MsgBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MsgBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MsgBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MsgBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MsgBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MsgBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MsgBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.MsgBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.MsgBody)
        MsgBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgBodyProto.internal_static_netty_MsgBody_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgBodyProto.internal_static_netty_MsgBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MsgBody.class, Builder.class);
      }

      // Construct using com.abin.lee.im.model.proto.MsgBodyProto.MsgBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "NoKnown";
        bitField0_ = (bitField0_ & ~0x00000002);
        passWord_ = "NoKnown";
        bitField0_ = (bitField0_ & ~0x00000004);
        bodyLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        messageType_ = 4;
        bitField0_ = (bitField0_ & ~0x00000010);
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgBodyProto.internal_static_netty_MsgBody_descriptor;
      }

      public MsgBody getDefaultInstanceForType() {
        return MsgBody.getDefaultInstance();
      }

      public MsgBody build() {
        MsgBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MsgBody buildPartial() {
        MsgBody result = new MsgBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.passWord_ = passWord_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bodyLength_ = bodyLength_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageType_ = messageType_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          address_ = address_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MsgBody) {
          return mergeFrom((MsgBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MsgBody other) {
        if (other == MsgBody.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasPassWord()) {
          bitField0_ |= 0x00000004;
          passWord_ = other.passWord_;
          onChanged();
        }
        if (other.hasBodyLength()) {
          setBodyLength(other.getBodyLength());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          return false;
        }
        if (!hasUserName()) {
          return false;
        }
        if (!hasPassWord()) {
          return false;
        }
        if (!hasBodyLength()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MsgBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MsgBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>required int64 userId = 1 [default = 0];</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 userId = 1 [default = 0];</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 1 [default = 0];</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 1 [default = 0];</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private Object userName_ = "NoKnown";
      /**
       * <code>required string userName = 2 [default = "NoKnown"];</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2 [default = "NoKnown"];</code>
       */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string userName = 2 [default = "NoKnown"];</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2 [default = "NoKnown"];</code>
       */
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2 [default = "NoKnown"];</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2 [default = "NoKnown"];</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      private Object passWord_ = "NoKnown";
      /**
       * <code>required string passWord = 3 [default = "NoKnown"];</code>
       */
      public boolean hasPassWord() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string passWord = 3 [default = "NoKnown"];</code>
       */
      public String getPassWord() {
        Object ref = passWord_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            passWord_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string passWord = 3 [default = "NoKnown"];</code>
       */
      public com.google.protobuf.ByteString
          getPassWordBytes() {
        Object ref = passWord_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          passWord_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string passWord = 3 [default = "NoKnown"];</code>
       */
      public Builder setPassWord(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passWord_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string passWord = 3 [default = "NoKnown"];</code>
       */
      public Builder clearPassWord() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passWord_ = getDefaultInstance().getPassWord();
        onChanged();
        return this;
      }
      /**
       * <code>required string passWord = 3 [default = "NoKnown"];</code>
       */
      public Builder setPassWordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        passWord_ = value;
        onChanged();
        return this;
      }

      private int bodyLength_ ;
      /**
       * <code>required int32 bodyLength = 4 [default = 0];</code>
       */
      public boolean hasBodyLength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 bodyLength = 4 [default = 0];</code>
       */
      public int getBodyLength() {
        return bodyLength_;
      }
      /**
       * <code>required int32 bodyLength = 4 [default = 0];</code>
       */
      public Builder setBodyLength(int value) {
        bitField0_ |= 0x00000008;
        bodyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bodyLength = 4 [default = 0];</code>
       */
      public Builder clearBodyLength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bodyLength_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ = 4;
      /**
       * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
       */
      public MessageType getMessageType() {
        MessageType result = MessageType.valueOf(messageType_);
        return result == null ? MessageType.PLATFORM : result;
      }
      /**
       * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
       */
      public Builder setMessageType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .netty.MsgBody.MessageType messageType = 5 [default = PLATFORM];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageType_ = 4;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          address_ = new com.google.protobuf.LazyStringArrayList(address_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressList() {
        return address_.getUnmodifiableView();
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public String getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes(int index) {
        return address_.getByteString(index);
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public Builder setAddress(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public Builder addAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public Builder addAllAddress(
          Iterable<String> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public Builder clearAddress() {
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string address = 6;</code>
       */
      public Builder addAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:netty.MsgBody)
    }

    // @@protoc_insertion_point(class_scope:netty.MsgBody)
    private static final MsgBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MsgBody();
    }

    public static MsgBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MsgBody>
        PARSER = new com.google.protobuf.AbstractParser<MsgBody>() {
      public MsgBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MsgBody(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MsgBody> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MsgBody> getParserForType() {
      return PARSER;
    }

    public MsgBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_MsgBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_netty_MsgBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023netty/MsgBody.proto\022\005netty\"\361\001\n\007MsgBody" +
      "\022\021\n\006userId\030\001 \002(\003:\0010\022\031\n\010userName\030\002 \002(\t:\007N" +
      "oKnown\022\031\n\010passWord\030\003 \002(\t:\007NoKnown\022\025\n\nbod" +
      "yLength\030\004 \002(\005:\0010\0229\n\013messageType\030\005 \001(\0162\032." +
      "netty.MsgBody.MessageType:\010PLATFORM\022\017\n\007a" +
      "ddress\030\006 \003(\t\":\n\013MessageType\022\007\n\003WEB\020\001\022\013\n\007" +
      "ANDROID\020\002\022\007\n\003IOS\020\003\022\014\n\010PLATFORM\020\004B+\n\033com." +
      "abin.lee.im.model.protoB\014MsgBodyProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_MsgBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_MsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_netty_MsgBody_descriptor,
        new String[] { "UserId", "UserName", "PassWord", "BodyLength", "MessageType", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
